# Generated by Django 6.0.4 on 2026-05-01 21:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movimentacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('tipo', models.CharField(choices=[('TRANSFERENCIA', 'Transferência entre fábricas'), ('EMPRESTIMO', 'Empréstimo Terceiros (MP)'), ('MATERIAIS', 'Materiais recebido como amostras'), ('RECEBIDO', 'Material recebido p/ transformação'), ('DEMONSTRACAO', 'Material recebido como demonstração'), ('ENTRADA', 'Entrada de acondicionamento'), ('REMESSA', 'Remessa merc. fatur. antecipado'), ('FABRICAS', 'Retorno empréstimos env. à terceiros'), ('DEVOLVER', 'Devoluções'), ('CONSERTO', 'Retorno de conserto'), ('TESTE', 'Material recebido para teste'), ('ACONDICIONAR', 'Retorno acondiciomento'), ('TRANSFORMAR', 'Retorno de material não transformado'), ('OUTROS', 'Outros')], max_length=50)),
                ('fornecedor', models.CharField(max_length=200)),
                ('nf', models.CharField(max_length=50)),
                ('cfop', models.CharField(max_length=20)),
                ('div', models.CharField(blank=True, max_length=20)),
                ('local', models.CharField(choices=[('VILA_VELHA', 'Vila Velha'), ('CARIACICA', 'Cariacica')], max_length=50)),
                ('placa', models.CharField(max_length=20)),
                ('obs', models.TextField(blank=True)),
                ('visto_patio', models.BooleanField(default=False)),
                ('visto_conferente', models.BooleanField(default=False)),
                ('cartao', models.CharField(blank=True, max_length=20)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('material', models.CharField()),
                ('unidade', models.CharField()),
                ('div', models.CharField()),
                ('descricao', models.TextField()),
                ('quantidade', models.IntegerField()),
                ('movimentacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='core.movimentacao')),
            ],
        ),
    ]
