# Generated by Django 6.0.4 on 2026-05-01 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movimentacao',
            name='cartao',
        ),
        migrations.AddField(
            model_name='movimentacao',
            name='cartao_conferente',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='movimentacao',
            name='cartao_patio',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
