# Generated by Django 6.0.4 on 2026-05-01 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_movimentacao_cartao_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['numero']},
        ),
        migrations.AlterField(
            model_name='movimentacao',
            name='tipo',
            field=models.CharField(choices=[('TRANSFERENCIA', 'Transferência entre fábricas'), ('EMPRESTIMO', 'Empréstimo Terceiros (MP)'), ('MATERIAIS', 'Materiais recebido como amostras'), ('RECEBIDO', 'Material recebido p/ transformação'), ('DEMONSTRACAO', 'Material recebido como demonstração'), ('ENTRADA', 'Entrada de acondicionamento'), ('REMESSA', 'Remessa merc. fatur. antecipado'), ('FABRICAS', 'Retorno empréstimos env. à terceiros'), ('DEVOLVER', 'Devoluções'), ('CONSERTO', 'Retorno de conserto'), ('TESTE', 'Material recebido para teste'), ('ACONDICIONAR', 'Retorno acondiciomento'), ('TRANSFORMAR', 'Retorno de material não transformado'), ('OUTROS', 'Outros:_____________________________')], max_length=50),
        ),
    ]
