# Generated by Django 6.0.4 on 2026-05-02 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_item_options_alter_movimentacao_tipo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={},
        ),
        migrations.AlterField(
            model_name='movimentacao',
            name='cfop',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
