# Generated by Django 6.0.4 on 2026-05-02 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_item_options_alter_movimentacao_cfop'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['numero']},
        ),
        migrations.AlterField(
            model_name='item',
            name='div',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='item',
            name='material',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='item',
            name='unidade',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='movimentacao',
            name='tipo',
            field=models.CharField(choices=[('TRANSFERENCIA', 'Transferência entre fábricas'), ('EMPRESTIMO', 'Empréstimo Terceiros (MP)'), ('MATERIAIS', 'Materiais recebido como amostras'), ('RECEBIDO', 'Material recebido p/ transformação'), ('DEMONSTRACAO', 'Material recebido como demonstração'), ('ENTRADA', 'Entrada de acondicionamento'), ('REMESSA', 'Remessa merc. fatur. antecipado'), ('FABRICAS', 'Retorno empréstimos env. à terceiros'), ('DEVOLVER', 'Devoluções'), ('CONSERTO', 'Retorno de conserto'), ('TESTE', 'Material recebido para teste'), ('ACONDICIONAR', 'Retorno acondicionamento'), ('TRANSFORMAR', 'Retorno de material não transformado'), ('OUTROS', 'Outros:...................')], max_length=50),
        ),
    ]
